AWSTemplateFormatVersion: 2010-09-09
Description: S3 Bucket
Parameters:
  S3BucketName:
    Type: String
Conditions:
  PreferedRegionCheck: !Equals [ !Ref AWS::Region, us-east-1 ]
Resources:
  S3BKF14:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        !If [ PreferedRegionCheck, !Join [ '-', [!Ref 'AWS::AccountId', !Ref 'S3BucketName'] ], !Join [ '-', [!Ref 'AWS::Region', !Ref 'S3BucketName'] ] ]