AWSTemplateFormatVersion: 2010-09-09
Description: S3 Bucket
Parameters:
  S3BucketName:
    Type: String
Resources:
  S3BKF14:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName